### ISSUE TITLE
eel.start 404 Not Found

### ISSUE THREAD

**Issue by ZJUAlexChen** [python-eel/Eel#639]
For PyCharm, according to the official document from [JetBrain](https://www.jetbrains.com/help/pycharm/editing-html-files.html#ws_html_preview_output), "The preview functionality relies on the PyCharm built-in web server. This server is always running and does not require any manual configuration. All the project files are served on the built-in server with the root URL `http://localhost:<built-in server port>/<project root>`, with respect to the project structure."
So, while directly eel.start(xxx, port=xxx), the webpage will be 404 Not Found, since the URL is missing the `<built-in server port>/<project root>` part. I wonder if I have any methods to modify the URL myself in eel.start. Thanks.

**Comment by ZJUAlexChen** [comment]
Just modify the "xxxx.html" with project directories and the problem is solved.

**Comment by DansDesigns** [comment]
same issue here, adding paths in the "xxx.html" call didnt solve it
